### ISSUE TITLE
Patch failed on OnePlus 6t

### ISSUE THREAD

**Issue by Strange-IPmart** [acervenky/projectduality#1]
OnePlus 6t (fajita).
OOS Q (v. 10.3.4).
Bootloader unlocked, rooted with latest Magisk. latest TWRP by Mauronofrio.
[mixer_paths_tavil.zip](https://github.com/acervenky/projectduality/files/5298815/mixer_paths_tavil.zip)
The error description is a screenshot contained in the zip above.
Many Thanks

**Comment by Maddoxx88** [comment]
Support for patch added [here](https://github.com/acervenky/projectduality/pull/2)
